spring:
  application:
    name: user-server
  profiles:
    active: dev
  config:
    # 在Spring Cloud 2020.0.0及以上版本中，spring.config.import是‌必需的‌，用于显式声明配置源（如Nacos、Consul等）。
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:common.yaml
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos注册中心地址
      username: nacos  # nacos账号
      password: nacos  # nacos密码
      config:
        namespace: gobbler # 命名空间
        group: GOBBLER_GROUP
        file-extension: yaml
      discovery:
        namespace: gobbler # 命名空间
        group: GOBBLER_GROUP