server:
  port: 11803
  servlet:
    context-path: /order
spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos注册中心地址
        username: nacos  # nacos账号
        password: nacos  # nacos密码
        namespace: gobbler # 命名空间